// ACTION
export const SET_PREDICTION_SEARCH = 'SET_PREDICTION_SEARCH';
export const SET_RESULT_SEARCH = 'SET_RESULT_SEARCH';
export const SET_RESULT_NGOS_SEARCH = 'SET_RESULT_NGOS_SEARCH';
export const SET_EXPERIENCE_ITEM_SEARCH = 'SET_EXPERIENCE_ITEM_SEARCH';
export const IS_LOADING_SEARCH = 'IS_LOADING_SEARCH';
export const SET_LIST_SEARCH = 'SET_LIST_SEARCH';
export const SET_ERROR_SEARCH = 'SET_ERROR_SEARCH';
export const IS_SUBMITTED_ONCE_SEARCH = 'IS_SUBMITTED_ONCE_SEARCH';
export const IS_BLOCKING_SEARCH = 'IS_BLOCKING_SEARCH';
export const RESET_SEARCH = 'RESET_SEARCH';
export const IS_LOADING_PREDICTION_SEARCH = 'IS_LOADING_PREDICTION_SEARCH';
export const SET_CACHED_RESULT_SEARCH = 'SET_CACHED_RESULT_SEARCH';
