// ACTION
export const SHOW_HEADER = 'SHOW_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';
export const SHOW_LOGO = 'SHOW_LOGO';
export const HIDE_LOGO = 'HIDE_LOGO';
export const SHOW_HAMBURGER_MENU = 'SHOW_HAMBURGER_MENU';
export const HIDE_HAMBURGER_MENU = 'HIDE_HAMBURGER_MENU';
export const TOGGLE_HAMBURGER_MENU = 'TOGGLE_HAMBURGER_MENU';
