// ACTION
export const RESET_GMAPS = 'RESET_GMAPS';
export const SHOW_GMAPS = 'SHOW_GMAPS';
export const HIDE_GMAPS = 'HIDE_GMAPS';
export const IS_INIT_GMAPS = 'IS_INIT_GMAPS';
export const IS_DISPOSED_GMAPS = 'IS_DISPOSED_GMAPS';
export const INIT_GMAPS = 'INIT_GMAPS';
export const HAS_SCRIPT_GMAPS = 'HAS_SCRIPT_GMAPS';
export const GET_SCRIPT_GMAPS = 'GET_SCRIPT_GMAPS';
export const INIT_POSITION_GMAPS = 'INIT_POSITION_GMAPS';
export const DISPOSE_GMAPS = 'DISPOSE_GMAPS';
export const IS_INIT_POSITION_GMAPS = 'IS_INIT_POSITION_GMAPS';
export const RESET_POSITION_GMAPS = 'RESET_POSITION_GMAPS';
