// LOCATION
export const HOMEPAGE = 'HOMEPAGE';
export const PARADE_DETAIL = 'PARADE_DETAIL';
export const REDIRECT = 'REDIRECT';
export const PARADE_EXPERIENCE = 'PARADE_EXPERIENCE';
export const PARADE_EXPERIENCE_HOTSPOT = 'PARADE_EXPERIENCE_HOTSPOT';
export const NOT_FOUND = 'NOT_FOUND';
